//APP
export const RESET_APPSTATE = "RESET_APPSTATE";
//Fetch API
export const FETCH_CATCH = "FETCH_CATCH";
//authen
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_EROR = "LOGIN_EROR";
export const LOGING = "LOGING";
export const LOGGED_IN = "LOGGED_IN";
export const LOGGED_OUT = "LOGGED_OUT";
export const EXPORT_FORM = "EXPORT_FORM";
export const AUTHEN_EXPRI = "AUTHEN_EXPRI";
//register
export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_EROR = "REGISTER_EROR";
export const REGISTING = "REGISTING";
export const REGISTER_CLEAR = "REGISTER_CLEAR";
export const DEFAULT = "DEFAULT";
//QUICK actions
export const SEARCH_MUSEUM = "SEARCH_MUSEUM";
export const SEARCHING_MUSEUM = "SEARCHING_MUSEUM";
export const SEARCH_MUSEUM_ERROR = "SEARCH_MUSEUM_ERROR";
export const SEARCH_MUSEUM_CLEAR_ERROR = "SEARCH_MUSEUM_CLEAR_ERROR";
//News actions
export const SEARCH_NEWS = "SEARCH_NEWS";
export const SEARCHING_NEWS = "SEARCHING_NEWS";
export const SEARCH_NEWS_ERROR = "SEARCH_NEWS_ERROR";
export const SEARCH_NEWS_CLEAR_ERROR = "SEARCH_NEWS_CLEAR_ERROR";
//MUSEUM DETAIL
export const SEARCH_MUSEUMDETAIL_ERROR="SEARCH_MUSEUMDETAIL_ERROR";
export const SEARCH_MUSEUMDETAIL_CLEAR_ERROR="SEARCH_MUSEUMDETAIL_CLEAR_ERROR"
export const SEARCHING_MUSEUMDETAIL="SEARCHING_MUSEUMDETAIL";
export const SEARCH_MUSEUMDETAIL="SEARCH_MUSEUMDETAIL";

export const SEARCH_AREA = "SEARCH_AREA";
export const SEARCHING_AREA = "SEARCHING_AREA";
export const SEARCH_AREA_ERROR = "SEARCH_AREA_ERROR";
export const SEARCH_AREA_CLEAR_ERROR = "SEARCH_AREA_CLEAR_ERROR";
//ANTIFACT
export const SEARCH_ANTIFACT = "SEARCH_ANTIFACT";
export const SEARCHING_ANTIFACT = "SEARCHING_ANTIFACT";
export const SEARCH_ANTIFACT_ERROR = "SEARCH_ANTIFACT_ERROR";
export const SEARCH_ANTIFACT_CLEAR_ERROR = "SEARCH_ANTIFACT_CLEAR_ERROR";

//ANTIFACT DETAIL
export const SEARCH_ANTIFACT_DETAIL = "SEARCH_ANTIFACT_DETAIL";
export const SEARCHING_ANTIFACT_DETAIL = "SEARCHING_ANTIFACT_DETAIL";
export const SEARCH_ANTIFACT_DETAIL_ERROR = "SEARCH_ANTIFACT_DETAIL_ERROR";
export const SEARCH_ANTIFACT_DETAIL_CLEAR_ERROR = "SEARCH_ANTIFACT_DETAIL_CLEAR_ERROR";
//ANTIFACT By tag
export const SEARCH_ANTIFACT_BY_TAG = "SEARCH_ANTIFACT_BY_TAG";
export const SEARCHING_ANTIFACT_BY_TAG = "SEARCHING_ANTIFACT_BY_TAG";
export const SEARCH_ANTIFACT_BY_TAG_ERROR = "SEARCH_ANTIFACT_BY_TAG_ERROR";
export const SEARCH_ANTIFACT_BY_TAG_CLEAR_ERROR = "SEARCH_ANTIFACT_BY_TAG_CLEAR_ERROR";
//ANTIFACT BY UUID
export const SEARCH_ANTIFACT_BY_UUID = "SEARCH_ANTIFACT_BY_UUID";
export const SEARCHING_ANTIFACT_BY_UUID = "SEARCHING_ANTIFACT_BY_UUID";
export const SEARCH_ANTIFACT_BY_UUID_ERROR = "SEARCH_ANTIFACT_BY_UUID_ERROR";
export const SEARCH_ANTIFACT_BY_UUID_CLEAR_ERROR = "SEARCH_ANTIFACT_BY_UUID_CLEAR_ERROR";
//ANTIFACT BY QRCODE
export const SEARCH_ANTIFACT_BY_QRCODE = "SEARCH_ANTIFACT_BY_QRCODE";
export const SEARCHING_ANTIFACT_BY_QRCODE = "SEARCHING_ANTIFACT_BY_QRCODE";
export const SEARCH_ANTIFACT_BY_QRCODE_ERROR = "SEARCH_ANTIFACT_BY_QRCODE_ERROR";
export const SEARCH_ANTIFACT_BY_QRCODE_CLEAR_ERROR = "SEARCH_ANTIFACT_BY_QRCODE_CLEAR_ERROR";

//search artifact actions
export const QUICK_SEARCH_ANTIFACT = "QUICK_SEARCH_ANTIFACT";
export const QUICK_SEARCHING_ANTIFACT = "QUICK_SEARCHING_ANTIFACT";
export const QUICK_SEARCH_ANTIFACT_ERROR = "QUICK_SEARCH_ANTIFACT_ERROR";
export const QUICK_SEARCH_ANTIFACT_CLEAR_ERROR = "QUICK_SEARCH_ANTIFACT_CLEAR_ERROR";
//QUICK_SEARCH_ALL
export const QUICK_SEARCH_ALL = "QUICK_SEARCH_ALL";
export const QUICK_SEARCHING_ALL = "QUICK_SEARCHING_ALL";
export const QUICK_SEARCH_ALL_ERROR = "QUICK_SEARCH_ALL_ERROR";
export const QUICK_SEARCH_ALL_CLEAR_ERROR = "QUICK_SEARCH_ALL_CLEAR_ERROR";
