//APP
export const RESET_APPSTATE="RESET_APPSTATE";
//Fetch API
export const FETCH_CATCH = "FETCH_CATCH";
//authen
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_EROR = "LOGIN_EROR";
export const LOGING = "LOGING";
export const LOGGED_IN = "LOGGED_IN";
export const LOGGED_OUT = "LOGGED_OUT";
export const EXPORT_FORM = "EXPORT_FORM";
export const AUTHEN_EXPRI = "AUTHEN_EXPRI";

export const DEFAULT = "DEFAULT";
//search actions
export const SEARCH_MUSEUM = "SEARCH_MUSEUM";
export const SEARCHING_MUSEUM = "SEARCHING_MUSEUM";
export const SEARCH_MUSEUM_ERROR = "SEARCH_MUSEUM_ERROR";
export const SEARCH_MUSEUM_CLEAR_ERROR = "SEARCH_CLEAR_ERROR";

export const SEARCH_AREA = "SEARCH_AREA";
export const SEARCHING_AREA = "SEARCHING_AREA";
export const SEARCH_AREA_ERROR = "SEARCH_AREA_ERROR";
export const SEARCH_AREA_CLEAR_ERROR = "SEARCH_AREA_CLEAR_ERROR";
//ANTIFACT
export const SEARCH_ANTIFACT = "SEARCH_ANTIFACT";
export const SEARCHING_ANTIFACT = "SEARCHING_ANTIFACT";
export const SEARCH_ANTIFACT_ERROR = "SEARCH_ANTIFACT_ERROR";
export const SEARCH_ANTIFACT_CLEAR_ERROR = "SEARCH_ANTIFACT_CLEAR_ERROR";
//ANTIFACT DETAIL
export const SEARCH_ANTIFACT_DETAIL = "SEARCH_ANTIFACT_DETAIL";
export const SEARCHING_ANTIFACT_DETAIL = "SEARCHING_ANTIFACT_DETAIL";
export const SEARCH_ANTIFACT_DETAIL_ERROR = "SEARCH_ANTIFACT_DETAIL_ERROR";
export const SEARCH_ANTIFACT_DETAIL_CLEAR_ERROR = "SEARCH_ANTIFACT_DETAIL_CLEAR_ERROR";
//ANTIFACT By tag
export const SEARCH_ANTIFACT_BY_TAG = "SEARCH_ANTIFACT_BY_TAG";
export const SEARCHING_ANTIFACT_BY_TAG = "SEARCHING_ANTIFACT_BY_TAG";
export const SEARCH_ANTIFACT_BY_TAG_ERROR = "SEARCH_ANTIFACT_BY_TAG_ERROR";
export const SEARCH_ANTIFACT_BY_TAG_CLEAR_ERROR = "SEARCH_ANTIFACT_BY_TAG_CLEAR_ERROR";